#!/bin/bash

if [ "x$1" == "x" ]; then

  echo "HELP: run task, task could be:"
  echo "  broker          start the http broker"
  echo "  center          start the sample center"
  echo "  hub             start the sample hub"
  echo "  dev             start the gulp watch for ui-dev"
  
  exit 1

fi

case $1 in 
  broker)
    node center/start_http_broker.js
    ;;
  center)
    ./center/center demo/sample/center/config.json
    ;;
  hub)
    ./hub/hub demo/sample/hub_a/config.json
    ;;
  hub_b)
    ./hub/hub demo/sample/hub_b/config.json
    ;;
  ui)
    cd ui-dev
    gulp watch
    ;;
  user)
    cd ui-user
    gulp watch
    ;;
esac
