#!/usr/bin/env node
// -*- mode: js -*-

var Center = require("./index");

var program = require("commander");
var fs = require("fs");
var _ = require("lodash");
var B = require("hope-base");
var S = require("hope-hub-center-shared");

var version = "3.0.0";

var categories = {
  "*":      false,
  "message": false,
  "center": true,
  "entity": false,
  "hub": false,
  "heartbeat": false,
  "wfe": false,
  "sm" : false
};

B.log.configure_categories(categories);

process.on("uncaughtException", function(err) {
    console.log(">>>>> Unhandled Exception >>>>>>");
    if (_.isError(err)) {
      console.log(err.stack);
    } else {
      console.log(B.to_string(err));
    }
});


program
  .version(version)
  .usage("[config-file]");

program.name = "center";

program.parse(process.argv);

if (program.args.length > 1) {
  program.help();
}

var config_file_path = program.args[0] || "./config.json";

var config = B.fs.read_json(config_file_path);

config.config_path = B.path.resolve(config_file_path);// the path of the config file

// TODO hard code the conversion of some paths currently, maybe need a more general solution
function _resolve_path(access_str) {
  var x = _.get(config, access_str);
  if (x) {
    if (_.isArray(x)) {
      var paths = x.map(function(p) {
        return B.path.abs(p, config.config_path);
      });
      _.set(config, access_str, paths);
    }
    else {
      _.set(config, access_str, B.path.abs(x, config.config_path));
    }
  }
} 
_resolve_path("assemble.dev_web_app.$params.static");
_resolve_path("assemble.user_web_app.$params.static");

// Fix the id of device and mnode
if (!config.id) {
  config.id = S.get_instance_id(
    B.path.abs("./.id", module.filename),
    B.path.resolve(config_file_path));
}

var mnode_params = _.get(config, "assemble.mnode.$params[1]");
if (mnode_params && !mnode_params.id) {
  mnode_params.id = config.id + "__mnode__";
}

S.enable_debug_shell();


process.on("SIGINT", function() {
  B.log("hope", "... CENTER EXITING ...");
  Center.stop$().then(function() {
    B.log("hope", "Center exit safely");
    process.exit(0);
  }).catch(function(err) {
    B.log.error("hope", "Error when center exit", err);
    process.exit(1);

  }).done();
});


Center.start$(config).done();



