/******************************************************************************
Copyright (c) 2016, Intel Corporation

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Intel Corporation nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*****************************************************************************/
var fs = require('fs');
var gulp = require("gulp");
var $ = require("gulp-load-plugins")();
var _ = require("lodash");

gulp.task("clean", function () {
  return gulp.src(["generated"], { read: false })
    .pipe($.rimraf());
});

gulp.task("plugins", function () {
  var exports = "//This file is generated by the gulp build script.\n\nmodule.exports = [\n";
  var m = 0;
  try {
    _.each(fs.readdirSync("./node_modules"), function(p) {
      if (_.startsWith(p, "hope-widget-") && fs.statSync("./node_modules/" + p).isDirectory()) {
        if (m++) {
          exports += ",\n";
        }
        exports += "  require('" + p + "')";
      }
    });
    exports += "\n];";

    //console.log(exports);
    fs.writeFileSync("./plugins.js", exports);

    // build pure json of plugins spec
    var specs = [];
    _.forEach(require("./plugins.js"), function(p) {
      if (_.isArray(p.specs)) {
        specs = specs.concat(p.specs);
      }
    });
    
    //console.log(JSON.stringify(specs));
    fs.writeFileSync("./plugins-specs.json", JSON.stringify(specs));
  }
  catch(e) {
    console.log(e);
  }
});

gulp.task("build", ["plugins"], function() {
  var opts = {
    optional: ["es7.classProperties"]
  };
  return gulp.src("widgets-jsx/**/*.js")
    .pipe($.babel(opts))
    .pipe(gulp.dest("generated"));
});

gulp.task("watch", function() {
  gulp.watch("widgets-jsx/**/*.js", ["build"]);
});
