/******************************************************************************
Copyright (c) 2016, Intel Corporation

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Intel Corporation nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*****************************************************************************/
module.exports = {
  "*NO* Binding": "*未绑定*",
  "__unknown__": "未命名",
  "Administrator": "管理员",
  "App": "应用",
  "App successfully removed!": "成功删除应用!",
  "Active Hub": "当前Hub",
  "Active Thing": "当前Thing",
  "Active Service": "当前Service",
  "Add Thing": "添加Thing",
  "Add Service": "添加Service",
  "Add tag without ports": "没有端口，无法添加标签",
  "Add New User": "添加新用户",
  "Advanced": "高级",
  "add new": "添加",
  "Apply": "应用",
  "Available": "当前可用的",
  "Apply to all hub": "应用到所有hub",
  "Add npm account": "添加npm账户",
  "Add": "添加",
  "Account": "账号",
  "Author": "作者",
  "Binding Type": "绑定方式",
  "Binding": "绑定",
  "Basic": "基本",
  "Back to the beginning": "回到起始时刻",
  //"Buffered Decorator": "",
  "Category": "分类",
  "Create": "新建",
  "Create App": "新建应用",
  "Create Workflow": "新建工作流",
  "Create UI": "新建UI",
  "Create Thing": "新建Thing",
  "Create Service": "新建Service",
  "Change the icon of node": "修改图标",
  "Change the icon": "修改图标",
  "Change the color": "修改颜色",
  "Change the name of port": "修改端口名称",
  "Change Password": "修改密码",
  "Confirm password": "密码确认",
  "Close": "关闭",
  "Click Here": "点击这里",
  "Cancel": "取消",
  "Cancel and back to edit": "取消并返回编辑",
  "Config": "配置",
  "Color": "颜色",
  "Continue": "继续自动播放",
  "Click to save the UI": "保存当前UI",
  "Click to delete the selected widgets": "删除当前选中的控件",
  "Click to stop the workflow": "停止当前工作流",
  "Click to show or hide the library": "显示或者隐藏库面板",
  "Click to run the workflow": "启动当前工作流",
  "Click to run the workflow with tracing": "调试运行当前工作流",
  "Click to save the workflow": "保存当前工作流",
  "Click to delete the selected objects": "删除当前选中的对象",
  "Click to fit the view": "自适应窗口尺寸",
  "Click to auto layout the workflow": "工作流自动布局",
  "Click to change theme": "修改主题",
  "Click to clear the output": "清除",
  "Click to select an icon": "点击选择图标",
  "Click each item for tips": "点击查看帮助",
  "Click to save the output": "保存",
  "Config required": "缺少必填项",
  //"Cached Decorator": "端口消息缓存",
  "debug this node": "调试此节点",
  "Default": "缺省",
  "Debug": "调试",
  "Delete": "删除",
  "Delete from Server": "从服务器上删除",
  "Double Click to edit the description": "双击编辑描述",
  "Double click the node to open configuration dialog, or": "双击节点打开配置界面，或者",
  "Description": "描述",
  "Drag to add tags": "拖拽到编辑框设置标签",
  "Drop here to delete": "拖拽到下面删除标签",
  "Details": "详情",
  "Demo": "演示",
  "Enable Replay": "允许重放",
  "Enter File Name": "输入文件名称",
  "Enter Name": "输入名称",
  "Enter Description": "输入描述",
  "Enter HTTP proxy": "输入HTTP代理",
  "Enter HTTPS proxy": "输入HTTPS代理",
  "Enter npm account name": "输入npm账号用户名",
  "Enter npm account password": "输入npm账号密码",
  "Enter npm account token": "输入npm账号token",
  "EndUser": "用户界面",
  "Edit": "编辑",
  "Edit Thing": "编辑Thing",
  "Edit Service": "编辑Service",
  "Edge": "边",
  "Extract Field": "字段提取",
  "Export": "导出",
  "Errors": "错误",
  "Error": "错误",
  "Error Infomation": "错误信息详情",

  "fixed": "静态指定",
  "Failed to load due to ": "加载失败，因为： ",
  "Failed to create app because": "创建应用失败，因为： ",
  "Failed to delete app because": "删除应用失败，因为： ",
  "Failed to update app because": "保存应用失败，因为： ",
  "Failed to show the workflow because": "显示工作流失败，因为： ",
  "Failed to show the UI because": "显示UI失败，因为： ",
  "Failed to start workflow because": "启动工作流失败，因为： ",
  "Failed to stop workflow because": "启动工作流失败，因为： ",
  "Failed to delete workflow because": "删除工作流失败，因为： ",
  "Failed to get workflow trace because": "获取工作流调试信息失败，因为： ",
  "Failed to send the data because": "发送数据失败，因为： ",
  "Failed to save workflow because": "保存工作流失败，因为： ",
  "Failed to save UI because": "保存UI失败，因为： ",
  "Failed to delete UI because": "删除UI失败，因为： ",
  "Failed to search!": "搜索失败!",
  "Failed to create thing!": "创建Thing失败!",
  "Failed to remove thing!": "删除Thing失败!",
  "Failed to update thing!": "更新Thing失败!",
  "Failed to install thing!": "安装Thing失败!",
  "Failed to create service!": "创建Service失败!",
  "Failed to remove service!": "删除Service失败!",
  "Failed to update service!": "更新Service失败!",
  "Failed to install thing!": "安装Service失败!",
  "Failed to delete user": "删除用户失败",
  "Failed to publish service, Error Code": "发布Service失败，错误代码",
  "For this workflow, we have some services that unable to resolve.": "在当前工作流中，我们还有些节点使用的服务无法定位。",
  "For this workflow, we have some services that unable to resolve, please rebind them manually.": "在当前工作流中，我们还有些节点使用的服务无法定位，请重新指派它们。",
  "Failed to export the workflow because": "导入工作流失败，因为： ",
  "Failed to export the UI because": "导入用户UI失败，因为： ",
  "Filter": "过滤器",
  "General": "通用",
  "Guest": "游客",
  "Help": "在线帮助",
  "Home": "首页",
  "HTTP proxy": "HTTP代理",
  "HTTPS proxy": "HTTPS代理",
  "Import": "导入",
  "Install Service": "安装Service",
  "Invalid name": "名称无效",
  "Invalid App name": "应用名称无效",
  "Invalid workflow name": "工作流名称无效",
  "Invalid workflow": "无效的工作流",
  "Invalid UI name": "UI名称无效",
  "Invalid UI": "无效的UI",
  "Invalid file name": "文件名称无效",
  "Invalid thing name": "Thing名称无效",
  "Invalid User name": "用户名无效",
  "Invalid service name": "Service名称无效",
  "Invalid configuration detected.": "检测到无效的配置项",
  "Invalid input": "无效输入",
  "Input": "输入",
  "Inspector": "属性面板",
  "Keywords": "关键字",
  "Last Created": "最近创建",
  "Last Modified": "最近修改",
  "Leave without SAVE": "不保存离开",
  "Leave": "离开",
  "Loading": "正在加载",
  "Library": "库面板",
  "Logout": "退出",
  "Lost Spec": "缺少Spec",
  "Lost Widget": "缺少Widget",
  "Lost Hub": "缺少Hub",
  "Lost Thing": "缺少Thing",
  "Lost Service": "缺少Service",
  "Message": "消息文本",
  "My App": "我的应用",
  "More": "更多",
  "New": "新建",
  "New File": "创建新文件",
  "New user": "新用户注册",
  "New password": "新密码",
  "Name": "名称",
  "No Store": "仅触发",
  "Not Found!": "页面未找到!",
  "No workflow found": "当前应用没有工作流",
  "No UI found": "当前应用没有UI",
  "Navigator": "缩略图",
  "NPM Account": "npm账户",
  "npm account successfully add": "npm账户添加成功",
  "OK": "确定",
  "Output": "输出",
  "Open": "打开",
  "Open Workflow": "打开工作流",
  "Open UI": "打开UI",
  "Other Apps": "其他应用",
  "Old password": "旧密码",
  "Package Files": "文件列表",
  "Password": "密码",
  "Password Confirm": "密码确认",
  "Password mismatched": "密码不匹配",
  "Proxy Settings": "代理设置",
  "Publish": "发布",
  "required config": "要求填写配置信息",
  "remove debug": "取消调试",
  "Regex": "正则表达式",
  "Run": "运行",
  "Replay": "重放",
  "Redo": "重做",
  "Reading operation encounter an error": "读操作出现错误",
  "Rebind": "重新绑定",
  "Rebinding": "重新绑定",
  "Role": "用户角色",
  "Search": "查找",
  "Select what to create": "选择新建目标类型",
  "Select any Node or Edge to view its information": "请选择节点或者边查看信息",
  "Status Control": "状态控制",
  "Stop": "停止",
  "Save": "保存",
  "Save All": "全部保存",
  "Save and Run": "保存并启动",
  "Specification": "规格描述",
  "Simple connection": "简单连接边",
  "Sign in": "登录",
  "Sign up": "注册",
  "Save to Server": "保存到服务器",
  "Step forward": "单步执行",
  "Step backward": "单步后退",
  "Service successfully created!": "成功创建Service!",
  "Service successfully deleted!": "成功删除Service!",
  "Service successfully updated!": "成功保存Service!",
  "Service successfully install!": "成功安装Service!",
  "Success to change password": "成功修改密码",
  "Success to delete user": "成功删除该用户",
  "Subsystem": "子系统",
  "Stack": "调用堆栈",
  "Show stack": "显示堆栈",
  "Start Installing. You may need wait for a moment. You can close this modal": "开始安装。稍等片刻，现在你可以关闭此对话框。",
  "This name already exists": "该名称已经存在",
  "This name already exists in the hub": "Hub下已存在该名称",
  "This name already exists in the thing": "Thing下已存在该名称",
  "This would delete the app deployed on the server. Please make sure this is what you expect!": "该操作将应用从服务器永久删除，确定要这样做吗？",
  "This would delete the workflow deployed on the server. Please make sure this is what you expect!": "该操作将工作流从服务器永久删除，确定要这样做吗？",
  "This would delete the ui deployed on the server. Please make sure this is what you expect!": "该操作将UI从服务器永久删除，确定要这样做吗？",
  "This would discard the changes of file. Please make sure this is what you expect!": "该操作将放弃对文件的修改，确定要这样做吗？",
  "This would discard the changes of workflow. Please make sure this is what you expect!": "该操作将放弃对工作流的修改，确定要这样做吗？",
  "This would discard the changes of UI. Please make sure this is what you expect!": "该操作将放弃对UI的修改，确定要这样做吗？",
  "This would delete the file on the server. Please make sure this is what you expect!": "该操作将文件从服务器永久删除，确定要这样做吗？",
  "This would overwrite the service deployed on the server. Please make sure this is what you expect!": "该操作将重写服务器上的文件，确定要这样做吗？",
  "This would overwrite the UI deployed on the server. Please make sure this is what you expect!": "该操作将重写服务器上的UI，确定要这样做吗？",
  "This would create or overwrite the workflow deployed on the server. Please make sure this is what you expect!": "该操作将新建或者重写服务器上的工作流，确定要这样做吗？",
  "This would delete the thing on the server. Please make sure this is what you expect!": "该操作将Thing从服务器永久删除，确定要这样做吗？",
  "This would delete the service on the server. Please make sure this is what you expect!": "该操作将Service从服务器永久删除，确定要这样做吗？",
  "This would delete the user and all apps included by. Please make sure this is what you expect!": "该操作将从服务器永久删除该用户以及所属应用，确定要这样做吗？",
  "This workflow looks like contain error(s), are you sure to deploy it on the server?": "当前工作流中好像有些错误，确定要保存它吗？",
  "This workflow looks like contain error(s), are you sure to deploy and start it?": "当前工作流中好像有些错误，确定要保存并启动它吗？",
  "This workflow looks like contain error(s), are you sure to start it?": "当前工作流中好像有些错误，确定启动它吗？",
  "This UI looks like contain error(s), are you sure to deploy it on the server?": "当前UI中好像有些错误，确定要保存它吗？",
  "This workflow looks like contain error(s), unable to deploy and start it?": "当前工作流中好像有些错误，不能保存并启动它！",
  "This workflow looks like contain error(s), unable to start it?": "当前工作流中好像有些错误，无法启动它！",
  "This workflow already exists": "该工作流已经存在",
  "This UI already exists": "该用户UI已经存在",
  "The name of this workflow already exists": "当前应用中已经存在该工作流的名称",
  "The name of this UI already exists": "当前应用中已经存在该用户UI的名称",
  "Tag": "标签",
  "Too many tags": "标签数量超过限制",
  "to see how to get your own token": "查看如何生成你自己的NPM令牌",
  "Tag in use": "该标签正在使用，无法删除",
  "Tips": "提示",
  "Thing successfully created!": "成功创建Thing!",
  "Thing successfully deleted!": "成功删除Thing!",
  "Thing successfully updated!": "成功保存Thing!",
  "Thing successfully install!": "成功安装Thing!",
  "Type": "类型",
  "UI successfully removed!": "成功删除UI!",
  "UI successfully saved!": "成功保存UI!",
  "UI successfully imported!": "成功导入UI!",
  "UI for End User": "用户UI",
  "UI Editor": "UI编辑器",
  "Users": "用户管理",
  "User Name": "用户名",
  "User does not exists, or incorrect password": "用户名不存在，或者密码错误",
  "User name exists": "用户名已经存在",
  "User Proxy": "用户代理",
  "User UI": "用户UI",
  "Unable to modify this attribute": "该节点禁止修改这个属性",
  "Unable to add port": "该节点禁止添加端口",
  "Unable to import workflow in this browser": "当前浏览器版本太低，无法导入工作流",
  "Unable to import UI in this browser": "当前浏览器版本太低，无法导入用户UI",
  "Unable to export workflow in this browser": "当前浏览器版本太低，无法导入工作流",
  "Unable to export UI in this browser": "当前浏览器版本太低，无法导入用户UI",
  "Unresolved Services": "无法定位的Service",
  "Unknown": "未知",
  "Unknown UI Widget": "未知UI控件",
  "Unknown Service": "未知Service",
  "Unknown Thing": "未知Thing",
  "Unknown Hub": "未知Hub",
  "Unnamed Service": "未命名Service",
  "Unnamed Thing": "未命名Thing",
  "Unnamed Hub": "未命名Hub",
  "User proxy successfully apply": "用户代理设置成功",
  "User Setting": "用户设置",
  "Undo": "撤销",
  "Value": "值",
  "Version": "版本",
  "Widgets": "控件",
  "Workflow": "工作流",
  "Workflow is running, please stop it before deleting": "工作流正在运行，请停止后删除",
  "Workflow successfully removed!": "成功删除工作流!",
  "Workflow successfully started!": "成功启动工作流!",
  "Workflow successfully saved!": "成功保存工作流!",
  "Workflow successfully imported!": "成功导入工作流!",
  "Workflow List": "工作流列表",
  "Workflow Editor": "工作流编辑器",
  "Workflow Rebinding": "工作流重绑定",
  "Workflow successfully stoped! Do you want replay slowly?": "成功停止工作流，需要重放和调试吗？",
  "Workflow successfully stoped!": "成功停止工作流!",
  "Workflow executed without tracing": "工作流没有调试信息",
  "Your edit is NOT saved! Are you READLLY want to leave?": "工作未保存，确定要放弃吗？",
  "YES": "是",
  "NO": "否",
  "write function": "编写函数",

  // Backend Errors
  "UNHANDLED_EXCEPTION": "出现未处理的异常",
  "CHECK_FAIL": "运行时检查失败",
};

